# This is the main config file for antons maze game. it is "fully" customizable ( as in you can change anything you like)
# if anything gets messed up, please redownload the config file from github


################################
maze.mainColor=Black
maze.altColor=aliceblue